// Open Library uses MARC/ISO 639-2 three-letter codes. This is a pragmatic subset covering
// what actually shows up in the Phase 0 sample — not a complete ISO 639-2 table. The real
// `language` table (ISO 639-1, docs/architecture.md §3.1) is Phase 1.1 work.
export const LANGUAGE_NAMES: Record<string, string> = {
  eng: 'English',
  rus: 'Russian',
  fre: 'French',
  fra: 'French',
  ger: 'German',
  deu: 'German',
  spa: 'Spanish',
  ita: 'Italian',
  por: 'Portuguese',
  dut: 'Dutch',
  nld: 'Dutch',
  swe: 'Swedish',
  nor: 'Norwegian',
  dan: 'Danish',
  fin: 'Finnish',
  pol: 'Polish',
  cze: 'Czech',
  ces: 'Czech',
  hun: 'Hungarian',
  gre: 'Greek',
  ell: 'Greek',
  tur: 'Turkish',
  heb: 'Hebrew',
  ara: 'Arabic',
  per: 'Persian',
  fas: 'Persian',
  hin: 'Hindi',
  ben: 'Bengali',
  chi: 'Chinese',
  zho: 'Chinese',
  jpn: 'Japanese',
  kor: 'Korean',
  vie: 'Vietnamese',
  tha: 'Thai',
  ukr: 'Ukrainian',
  bul: 'Bulgarian',
  rum: 'Romanian',
  ron: 'Romanian',
  cat: 'Catalan',
  arm: 'Armenian',
  hye: 'Armenian',
  yid: 'Yiddish',
  pan: 'Punjabi',
  ice: 'Icelandic',
  isl: 'Icelandic',
  ind: 'Indonesian',
  may: 'Malay',
  msa: 'Malay',
  und: 'Undetermined',
};

export function languageName(code: string): string {
  return LANGUAGE_NAMES[code] ?? code;
}
