/**
 * ISO 639-2/B ("bibliographic", 3-letter) → ISO 639-1 (2-letter) for the same language set as
 * `LANGUAGE_NAMES`. Open Library (and MARC records generally) report languages as 639-2/B codes
 * — e.g. `"eng"`, `"rus"`, `"ger"` — not 639-1. Without this mapping, `LanguageCode.create`
 * rejects every real-world Open Library language code, silently dropping nearly every edition in
 * `SyncWorkFromSource` (caught before it shipped: a test using realistic 3-letter codes failed
 * where one using fabricated 2-letter codes had passed).
 *
 * A handful of languages have divergent bibliographic (/B) vs terminological (/T) 3-letter
 * codes (e.g. German is `ger`/B vs `deu`/T) — MARC and Open Library use /B, so that's what's
 * mapped here; the /T form isn't included and will fail to parse until something actually needs it.
 */
export const ISO_639_2B_TO_1: ReadonlyMap<string, string> = new Map(
  Object.entries({
    aar: 'aa',
    abk: 'ab',
    afr: 'af',
    amh: 'am',
    ara: 'ar',
    aze: 'az',
    bel: 'be',
    bul: 'bg',
    ben: 'bn',
    tib: 'bo',
    bos: 'bs',
    cat: 'ca',
    cze: 'cs',
    wel: 'cy',
    dan: 'da',
    ger: 'de',
    gre: 'el',
    eng: 'en',
    epo: 'eo',
    spa: 'es',
    est: 'et',
    baq: 'eu',
    per: 'fa',
    fin: 'fi',
    fre: 'fr',
    gle: 'ga',
    glg: 'gl',
    guj: 'gu',
    heb: 'he',
    hin: 'hi',
    hrv: 'hr',
    hun: 'hu',
    arm: 'hy',
    ind: 'id',
    ice: 'is',
    ita: 'it',
    jpn: 'ja',
    geo: 'ka',
    kaz: 'kk',
    khm: 'km',
    kan: 'kn',
    kor: 'ko',
    kur: 'ku',
    kir: 'ky',
    lat: 'la',
    lao: 'lo',
    lit: 'lt',
    lav: 'lv',
    mac: 'mk',
    mal: 'ml',
    mon: 'mn',
    mar: 'mr',
    may: 'ms',
    mlt: 'mt',
    bur: 'my',
    nep: 'ne',
    dut: 'nl',
    nor: 'no',
    pan: 'pa',
    pol: 'pl',
    pus: 'ps',
    por: 'pt',
    rum: 'ro',
    rus: 'ru',
    kin: 'rw',
    snd: 'sd',
    sin: 'si',
    slo: 'sk',
    slv: 'sl',
    som: 'so',
    alb: 'sq',
    srp: 'sr',
    swe: 'sv',
    swa: 'sw',
    tam: 'ta',
    tel: 'te',
    tgk: 'tg',
    tha: 'th',
    tuk: 'tk',
    tur: 'tr',
    ukr: 'uk',
    urd: 'ur',
    uzb: 'uz',
    vie: 'vi',
    yid: 'yi',
    chi: 'zh',
    zul: 'zu',
  }),
);
