/**
 * The complete ISO 639-1 set (183 codes), with English and Russian names.
 *
 * Completeness is a correctness requirement, not a nicety: `SyncWorkFromSource` *skips* any
 * edition whose language it cannot parse, so a missing code silently drops that edition — real
 * data loss found live in Phase 3, when the table held only 87 "likely" codes.
 *
 * Names were generated once from the platform's ICU data (`Intl.DisplayNames`) and committed as
 * a static table rather than computed at runtime: `packages/domain` must stay dependency-free and
 * deterministic, and ICU data varies between Node builds — while these names are seeded into the
 * `language` table, where they must not drift with the runtime.
 */
export interface LanguageNames {
  readonly nameEn: string;
  readonly nameRu: string;
}

export const LANGUAGE_NAMES: ReadonlyMap<string, LanguageNames> = new Map(
  Object.entries({
    aa: { nameEn: 'Afar', nameRu: 'афарский' },
    ab: { nameEn: 'Abkhazian', nameRu: 'абхазский' },
    ae: { nameEn: 'Avestan', nameRu: 'авестийский' },
    af: { nameEn: 'Afrikaans', nameRu: 'африкаанс' },
    ak: { nameEn: 'Akan', nameRu: 'акан' },
    am: { nameEn: 'Amharic', nameRu: 'амхарский' },
    an: { nameEn: 'Aragonese', nameRu: 'арагонский' },
    ar: { nameEn: 'Arabic', nameRu: 'арабский' },
    as: { nameEn: 'Assamese', nameRu: 'ассамский' },
    av: { nameEn: 'Avaric', nameRu: 'аварский' },
    ay: { nameEn: 'Aymara', nameRu: 'аймара' },
    az: { nameEn: 'Azerbaijani', nameRu: 'азербайджанский' },
    ba: { nameEn: 'Bashkir', nameRu: 'башкирский' },
    be: { nameEn: 'Belarusian', nameRu: 'белорусский' },
    bg: { nameEn: 'Bulgarian', nameRu: 'болгарский' },
    bi: { nameEn: 'Bislama', nameRu: 'бислама' },
    bm: { nameEn: 'Bambara', nameRu: 'бамбара' },
    bn: { nameEn: 'Bangla', nameRu: 'бенгальский' },
    bo: { nameEn: 'Tibetan', nameRu: 'тибетский' },
    br: { nameEn: 'Breton', nameRu: 'бретонский' },
    bs: { nameEn: 'Bosnian', nameRu: 'боснийский' },
    ca: { nameEn: 'Catalan', nameRu: 'каталанский' },
    ce: { nameEn: 'Chechen', nameRu: 'чеченский' },
    ch: { nameEn: 'Chamorro', nameRu: 'чаморро' },
    co: { nameEn: 'Corsican', nameRu: 'корсиканский' },
    cr: { nameEn: 'Cree', nameRu: 'кри' },
    cs: { nameEn: 'Czech', nameRu: 'чешский' },
    cu: { nameEn: 'Church Slavic', nameRu: 'церковнославянский' },
    cv: { nameEn: 'Chuvash', nameRu: 'чувашский' },
    cy: { nameEn: 'Welsh', nameRu: 'валлийский' },
    da: { nameEn: 'Danish', nameRu: 'датский' },
    de: { nameEn: 'German', nameRu: 'немецкий' },
    dv: { nameEn: 'Divehi', nameRu: 'мальдивский' },
    dz: { nameEn: 'Dzongkha', nameRu: 'дзонг-кэ' },
    ee: { nameEn: 'Ewe', nameRu: 'эве' },
    el: { nameEn: 'Greek', nameRu: 'греческий' },
    en: { nameEn: 'English', nameRu: 'английский' },
    eo: { nameEn: 'Esperanto', nameRu: 'эсперанто' },
    es: { nameEn: 'Spanish', nameRu: 'испанский' },
    et: { nameEn: 'Estonian', nameRu: 'эстонский' },
    eu: { nameEn: 'Basque', nameRu: 'баскский' },
    fa: { nameEn: 'Persian', nameRu: 'персидский' },
    ff: { nameEn: 'Fula', nameRu: 'фулах' },
    fi: { nameEn: 'Finnish', nameRu: 'финский' },
    fj: { nameEn: 'Fijian', nameRu: 'фиджи' },
    fo: { nameEn: 'Faroese', nameRu: 'фарерский' },
    fr: { nameEn: 'French', nameRu: 'французский' },
    fy: { nameEn: 'Western Frisian', nameRu: 'западнофризский' },
    ga: { nameEn: 'Irish', nameRu: 'ирландский' },
    gd: { nameEn: 'Scottish Gaelic', nameRu: 'гэльский' },
    gl: { nameEn: 'Galician', nameRu: 'галисийский' },
    gn: { nameEn: 'Guarani', nameRu: 'гуарани' },
    gu: { nameEn: 'Gujarati', nameRu: 'гуджарати' },
    gv: { nameEn: 'Manx', nameRu: 'мэнский' },
    ha: { nameEn: 'Hausa', nameRu: 'хауса' },
    he: { nameEn: 'Hebrew', nameRu: 'иврит' },
    hi: { nameEn: 'Hindi', nameRu: 'хинди' },
    ho: { nameEn: 'Hiri Motu', nameRu: 'хиримоту' },
    hr: { nameEn: 'Croatian', nameRu: 'хорватский' },
    ht: { nameEn: 'Haitian Creole', nameRu: 'гаитянский' },
    hu: { nameEn: 'Hungarian', nameRu: 'венгерский' },
    hy: { nameEn: 'Armenian', nameRu: 'армянский' },
    hz: { nameEn: 'Herero', nameRu: 'гереро' },
    ia: { nameEn: 'Interlingua', nameRu: 'интерлингва' },
    id: { nameEn: 'Indonesian', nameRu: 'индонезийский' },
    ie: { nameEn: 'Interlingue', nameRu: 'интерлингве' },
    ig: { nameEn: 'Igbo', nameRu: 'игбо' },
    ii: { nameEn: 'Sichuan Yi', nameRu: 'носу' },
    ik: { nameEn: 'Inupiaq', nameRu: 'инупиак' },
    io: { nameEn: 'Ido', nameRu: 'идо' },
    is: { nameEn: 'Icelandic', nameRu: 'исландский' },
    it: { nameEn: 'Italian', nameRu: 'итальянский' },
    iu: { nameEn: 'Inuktitut', nameRu: 'инуктитут' },
    ja: { nameEn: 'Japanese', nameRu: 'японский' },
    jv: { nameEn: 'Javanese', nameRu: 'яванский' },
    ka: { nameEn: 'Georgian', nameRu: 'грузинский' },
    kg: { nameEn: 'Kongo', nameRu: 'конго' },
    ki: { nameEn: 'Kikuyu', nameRu: 'кикуйю' },
    kj: { nameEn: 'Kuanyama', nameRu: 'кунама' },
    kk: { nameEn: 'Kazakh', nameRu: 'казахский' },
    kl: { nameEn: 'Kalaallisut', nameRu: 'гренландский' },
    km: { nameEn: 'Khmer', nameRu: 'кхмерский' },
    kn: { nameEn: 'Kannada', nameRu: 'каннада' },
    ko: { nameEn: 'Korean', nameRu: 'корейский' },
    kr: { nameEn: 'Kanuri', nameRu: 'канури' },
    ks: { nameEn: 'Kashmiri', nameRu: 'кашмири' },
    ku: { nameEn: 'Kurdish', nameRu: 'курдский' },
    kv: { nameEn: 'Komi', nameRu: 'коми' },
    kw: { nameEn: 'Cornish', nameRu: 'корнский' },
    ky: { nameEn: 'Kyrgyz', nameRu: 'киргизский' },
    la: { nameEn: 'Latin', nameRu: 'латинский' },
    lb: { nameEn: 'Luxembourgish', nameRu: 'люксембургский' },
    lg: { nameEn: 'Ganda', nameRu: 'ганда' },
    li: { nameEn: 'Limburgish', nameRu: 'лимбургский' },
    ln: { nameEn: 'Lingala', nameRu: 'лингала' },
    lo: { nameEn: 'Lao', nameRu: 'лаосский' },
    lt: { nameEn: 'Lithuanian', nameRu: 'литовский' },
    lu: { nameEn: 'Luba-Katanga', nameRu: 'луба-катанга' },
    lv: { nameEn: 'Latvian', nameRu: 'латышский' },
    mg: { nameEn: 'Malagasy', nameRu: 'малагасийский' },
    mh: { nameEn: 'Marshallese', nameRu: 'маршалльский' },
    mi: { nameEn: 'Māori', nameRu: 'маори' },
    mk: { nameEn: 'Macedonian', nameRu: 'македонский' },
    ml: { nameEn: 'Malayalam', nameRu: 'малаялам' },
    mn: { nameEn: 'Mongolian', nameRu: 'монгольский' },
    mr: { nameEn: 'Marathi', nameRu: 'маратхи' },
    ms: { nameEn: 'Malay', nameRu: 'малайский' },
    mt: { nameEn: 'Maltese', nameRu: 'мальтийский' },
    my: { nameEn: 'Burmese', nameRu: 'бирманский' },
    na: { nameEn: 'Nauru', nameRu: 'науру' },
    nb: { nameEn: 'Norwegian Bokmål', nameRu: 'норвежский букмол' },
    nd: { nameEn: 'North Ndebele', nameRu: 'северный ндебеле' },
    ne: { nameEn: 'Nepali', nameRu: 'непальский' },
    ng: { nameEn: 'Ndonga', nameRu: 'ндонга' },
    nl: { nameEn: 'Dutch', nameRu: 'нидерландский' },
    nn: { nameEn: 'Norwegian Nynorsk', nameRu: 'нюнорск' },
    no: { nameEn: 'Norwegian', nameRu: 'норвежский' },
    nr: { nameEn: 'South Ndebele', nameRu: 'южный ндебеле' },
    nv: { nameEn: 'Navajo', nameRu: 'навахо' },
    ny: { nameEn: 'Nyanja', nameRu: 'ньянджа' },
    oc: { nameEn: 'Occitan', nameRu: 'окситанский' },
    oj: { nameEn: 'Ojibwa', nameRu: 'оджибва' },
    om: { nameEn: 'Oromo', nameRu: 'оромо' },
    or: { nameEn: 'Odia', nameRu: 'ория' },
    os: { nameEn: 'Ossetic', nameRu: 'осетинский' },
    pa: { nameEn: 'Punjabi', nameRu: 'панджаби' },
    pi: { nameEn: 'Pali', nameRu: 'пали' },
    pl: { nameEn: 'Polish', nameRu: 'польский' },
    ps: { nameEn: 'Pashto', nameRu: 'пушту' },
    pt: { nameEn: 'Portuguese', nameRu: 'португальский' },
    qu: { nameEn: 'Quechua', nameRu: 'кечуа' },
    rm: { nameEn: 'Romansh', nameRu: 'романшский' },
    rn: { nameEn: 'Rundi', nameRu: 'рунди' },
    ro: { nameEn: 'Romanian', nameRu: 'румынский' },
    ru: { nameEn: 'Russian', nameRu: 'русский' },
    rw: { nameEn: 'Kinyarwanda', nameRu: 'киньяруанда' },
    sa: { nameEn: 'Sanskrit', nameRu: 'санскрит' },
    sc: { nameEn: 'Sardinian', nameRu: 'сардинский' },
    sd: { nameEn: 'Sindhi', nameRu: 'синдхи' },
    se: { nameEn: 'Northern Sami', nameRu: 'северносаамский' },
    sg: { nameEn: 'Sango', nameRu: 'санго' },
    si: { nameEn: 'Sinhala', nameRu: 'сингальский' },
    sk: { nameEn: 'Slovak', nameRu: 'словацкий' },
    sl: { nameEn: 'Slovenian', nameRu: 'словенский' },
    sm: { nameEn: 'Samoan', nameRu: 'самоанский' },
    sn: { nameEn: 'Shona', nameRu: 'шона' },
    so: { nameEn: 'Somali', nameRu: 'сомали' },
    sq: { nameEn: 'Albanian', nameRu: 'албанский' },
    sr: { nameEn: 'Serbian', nameRu: 'сербский' },
    ss: { nameEn: 'Swati', nameRu: 'свази' },
    st: { nameEn: 'Southern Sotho', nameRu: 'южный сото' },
    su: { nameEn: 'Sundanese', nameRu: 'сунданский' },
    sv: { nameEn: 'Swedish', nameRu: 'шведский' },
    sw: { nameEn: 'Swahili', nameRu: 'суахили' },
    ta: { nameEn: 'Tamil', nameRu: 'тамильский' },
    te: { nameEn: 'Telugu', nameRu: 'телугу' },
    tg: { nameEn: 'Tajik', nameRu: 'таджикский' },
    th: { nameEn: 'Thai', nameRu: 'тайский' },
    ti: { nameEn: 'Tigrinya', nameRu: 'тигринья' },
    tk: { nameEn: 'Turkmen', nameRu: 'туркменский' },
    tl: { nameEn: 'Filipino', nameRu: 'филиппинский' },
    tn: { nameEn: 'Tswana', nameRu: 'тсвана' },
    to: { nameEn: 'Tongan', nameRu: 'тонганский' },
    tr: { nameEn: 'Turkish', nameRu: 'турецкий' },
    ts: { nameEn: 'Tsonga', nameRu: 'тсонга' },
    tt: { nameEn: 'Tatar', nameRu: 'татарский' },
    tw: { nameEn: 'Akan', nameRu: 'акан' },
    ty: { nameEn: 'Tahitian', nameRu: 'таитянский' },
    ug: { nameEn: 'Uyghur', nameRu: 'уйгурский' },
    uk: { nameEn: 'Ukrainian', nameRu: 'украинский' },
    ur: { nameEn: 'Urdu', nameRu: 'урду' },
    uz: { nameEn: 'Uzbek', nameRu: 'узбекский' },
    ve: { nameEn: 'Venda', nameRu: 'венда' },
    vi: { nameEn: 'Vietnamese', nameRu: 'вьетнамский' },
    vo: { nameEn: 'Volapük', nameRu: 'волапюк' },
    wa: { nameEn: 'Walloon', nameRu: 'валлонский' },
    wo: { nameEn: 'Wolof', nameRu: 'волоф' },
    xh: { nameEn: 'Xhosa', nameRu: 'коса' },
    yi: { nameEn: 'Yiddish', nameRu: 'идиш' },
    yo: { nameEn: 'Yoruba', nameRu: 'йоруба' },
    za: { nameEn: 'Zhuang', nameRu: 'чжуань' },
    zh: { nameEn: 'Chinese', nameRu: 'китайский' },
    zu: { nameEn: 'Zulu', nameRu: 'зулу' },
  }),
);
