/**
 * ISO 639-1 codes actually likely to show up in book metadata from Open Library / Google Books /
 * WorldCat. Not the full 184-code standard — extend via PR when a real source hits an unmapped
 * code (`LanguageCode.create` throws with the raw code in the message, so gaps are visible in
 * logs/tests, not silently swallowed). This is the source of truth seeded into the `language`
 * table in Phase 1.2 (docs/architecture.md §3.1).
 */
export interface LanguageNames {
  readonly nameEn: string;
  readonly nameRu: string;
}

export const LANGUAGE_NAMES: ReadonlyMap<string, LanguageNames> = new Map(
  Object.entries({
    aa: { nameEn: 'Afar', nameRu: 'афарский' },
    ab: { nameEn: 'Abkhazian', nameRu: 'абхазский' },
    af: { nameEn: 'Afrikaans', nameRu: 'африкаанс' },
    am: { nameEn: 'Amharic', nameRu: 'амхарский' },
    ar: { nameEn: 'Arabic', nameRu: 'арабский' },
    az: { nameEn: 'Azerbaijani', nameRu: 'азербайджанский' },
    be: { nameEn: 'Belarusian', nameRu: 'белорусский' },
    bg: { nameEn: 'Bulgarian', nameRu: 'болгарский' },
    bn: { nameEn: 'Bengali', nameRu: 'бенгальский' },
    bo: { nameEn: 'Tibetan', nameRu: 'тибетский' },
    bs: { nameEn: 'Bosnian', nameRu: 'боснийский' },
    ca: { nameEn: 'Catalan', nameRu: 'каталанский' },
    cs: { nameEn: 'Czech', nameRu: 'чешский' },
    cy: { nameEn: 'Welsh', nameRu: 'валлийский' },
    da: { nameEn: 'Danish', nameRu: 'датский' },
    de: { nameEn: 'German', nameRu: 'немецкий' },
    el: { nameEn: 'Greek', nameRu: 'греческий' },
    en: { nameEn: 'English', nameRu: 'английский' },
    eo: { nameEn: 'Esperanto', nameRu: 'эсперанто' },
    es: { nameEn: 'Spanish', nameRu: 'испанский' },
    et: { nameEn: 'Estonian', nameRu: 'эстонский' },
    eu: { nameEn: 'Basque', nameRu: 'баскский' },
    fa: { nameEn: 'Persian', nameRu: 'персидский' },
    fi: { nameEn: 'Finnish', nameRu: 'финский' },
    fr: { nameEn: 'French', nameRu: 'французский' },
    ga: { nameEn: 'Irish', nameRu: 'ирландский' },
    gl: { nameEn: 'Galician', nameRu: 'галисийский' },
    gu: { nameEn: 'Gujarati', nameRu: 'гуджарати' },
    he: { nameEn: 'Hebrew', nameRu: 'иврит' },
    hi: { nameEn: 'Hindi', nameRu: 'хинди' },
    hr: { nameEn: 'Croatian', nameRu: 'хорватский' },
    hu: { nameEn: 'Hungarian', nameRu: 'венгерский' },
    hy: { nameEn: 'Armenian', nameRu: 'армянский' },
    id: { nameEn: 'Indonesian', nameRu: 'индонезийский' },
    is: { nameEn: 'Icelandic', nameRu: 'исландский' },
    it: { nameEn: 'Italian', nameRu: 'итальянский' },
    ja: { nameEn: 'Japanese', nameRu: 'японский' },
    ka: { nameEn: 'Georgian', nameRu: 'грузинский' },
    kk: { nameEn: 'Kazakh', nameRu: 'казахский' },
    km: { nameEn: 'Khmer', nameRu: 'кхмерский' },
    kn: { nameEn: 'Kannada', nameRu: 'каннада' },
    ko: { nameEn: 'Korean', nameRu: 'корейский' },
    ku: { nameEn: 'Kurdish', nameRu: 'курдский' },
    ky: { nameEn: 'Kyrgyz', nameRu: 'киргизский' },
    la: { nameEn: 'Latin', nameRu: 'латынь' },
    lo: { nameEn: 'Lao', nameRu: 'лаосский' },
    lt: { nameEn: 'Lithuanian', nameRu: 'литовский' },
    lv: { nameEn: 'Latvian', nameRu: 'латышский' },
    mk: { nameEn: 'Macedonian', nameRu: 'македонский' },
    ml: { nameEn: 'Malayalam', nameRu: 'малаялам' },
    mn: { nameEn: 'Mongolian', nameRu: 'монгольский' },
    mr: { nameEn: 'Marathi', nameRu: 'маратхи' },
    ms: { nameEn: 'Malay', nameRu: 'малайский' },
    mt: { nameEn: 'Maltese', nameRu: 'мальтийский' },
    my: { nameEn: 'Burmese', nameRu: 'бирманский' },
    ne: { nameEn: 'Nepali', nameRu: 'непальский' },
    nl: { nameEn: 'Dutch', nameRu: 'нидерландский' },
    no: { nameEn: 'Norwegian', nameRu: 'норвежский' },
    pa: { nameEn: 'Punjabi', nameRu: 'панджаби' },
    pl: { nameEn: 'Polish', nameRu: 'польский' },
    ps: { nameEn: 'Pashto', nameRu: 'пушту' },
    pt: { nameEn: 'Portuguese', nameRu: 'португальский' },
    ro: { nameEn: 'Romanian', nameRu: 'румынский' },
    ru: { nameEn: 'Russian', nameRu: 'русский' },
    rw: { nameEn: 'Kinyarwanda', nameRu: 'киньяруанда' },
    sd: { nameEn: 'Sindhi', nameRu: 'синдхи' },
    si: { nameEn: 'Sinhala', nameRu: 'сингальский' },
    sk: { nameEn: 'Slovak', nameRu: 'словацкий' },
    sl: { nameEn: 'Slovenian', nameRu: 'словенский' },
    so: { nameEn: 'Somali', nameRu: 'сомалийский' },
    sq: { nameEn: 'Albanian', nameRu: 'албанский' },
    sr: { nameEn: 'Serbian', nameRu: 'сербский' },
    sv: { nameEn: 'Swedish', nameRu: 'шведский' },
    sw: { nameEn: 'Swahili', nameRu: 'суахили' },
    ta: { nameEn: 'Tamil', nameRu: 'тамильский' },
    te: { nameEn: 'Telugu', nameRu: 'телугу' },
    tg: { nameEn: 'Tajik', nameRu: 'таджикский' },
    th: { nameEn: 'Thai', nameRu: 'тайский' },
    tk: { nameEn: 'Turkmen', nameRu: 'туркменский' },
    tr: { nameEn: 'Turkish', nameRu: 'турецкий' },
    uk: { nameEn: 'Ukrainian', nameRu: 'украинский' },
    ur: { nameEn: 'Urdu', nameRu: 'урду' },
    uz: { nameEn: 'Uzbek', nameRu: 'узбекский' },
    vi: { nameEn: 'Vietnamese', nameRu: 'вьетнамский' },
    yi: { nameEn: 'Yiddish', nameRu: 'идиш' },
    zh: { nameEn: 'Chinese', nameRu: 'китайский' },
    zu: { nameEn: 'Zulu', nameRu: 'зулусский' },
  }),
);
